FROM blang/latex:ubuntu

# Install biber and latexrun
RUN apt-get update -q \
    && apt-get install -qy biber texlive-bibtex-extra git python3 \
    && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/aclements/latexrun.git /opt/latexrun && cp /opt/latexrun/latexrun /usr/local/bin/latexrun && chmod +x /usr/local/bin/latexrun