assign [class="Mattermost"] $ws2

assign [class="Todoist"] $ws3
assign [class="Morgen"] $ws3

assign [class="Spotify"] $ws4

bindsym $mod+Shift+v exec /usr/bin/flatpak run com.github.hluk.copyq toggle
for_window [class="copyq"] floating enable

