exec_always --no-startup-id setxkbmap -option ctrl:nocaps -option shift:both_capslock_cancel

workspace $ws2 output HDMI-A-1-1
workspace $ws3 output HDMI-A-1-1
workspace $ws4 output HDMI-A-1-1

assign [class="Mattermost"] $ws2

assign [class="Todoist"] $ws3
assign [class="Morgen"] $ws3

assign [class="Spotify"] $ws4
