exec_always --no-startup-id setxkbmap -option ctrl:nocaps -option shift:both_capslock_cancel

workspace 2 output HDMI-A-1-1
assign [class="Mattermost"] $ws2

workspace 3 output HDMI-A-1-1
assign [class="Todoist"] $ws3
assign [class="Morgen"] $ws3
