#!/bin/bash

this_path=$(readlink -f $0)        ## Path of this file including filename
dir_name=`dirname ${this_path}`    ## Dir where this file is
myname=`basename ${this_path}`     ## file name of this script.
logger="${myname}.log"

restore='false'

function usage {
  echo "
  usage: $myname [options] <manifest-file>

  -h           optional  Print this help message
  -q           optional  Suppress log messages on screen, just log them.
  -l <log>     optional  print errors and output to this file.
               default   ${myname}.log
  -r           optional  Run a restore instead of a backup"
  exit 1
}

function logit {
  if [[ $quiet == "true" ]]
  then
    echo $1 1>> $logger
  else
    echo $1 |tee -a $logger
  fi
}

logit "Initializing `date`"

## Start coding from here. Some basic flags are already provide. Feel free to override, add, delete
while getopts :hql:r args
do
  case $args in
  h) usage ;;
  q) quiet='true' ;; ## Suppress messages, just log them.
  l) logger="$OPTARG" ;;
  r) restore='true' ;;
  :) logit "The argument -$OPTARG requires a parameter" ;;
  *) usage ;;
  esac
done

## Do parameter validations here.
manifest_file=${@:$OPTIND:1}
if [[ ! -f $manifest_file ]]
then
  echo ""
  logit "Manifest file $manifest does not exist or is not readable !!"
  usage
fi

backup_location=$(head -n 1 ${manifest_file})
if [[ ! -d $backup_location ]]
then
  echo ""
  logit "Backup location $backup_location does not exist or is not a directory !!"
  usage
fi

function backup {
  logit "Running backup operation to $backup_location"
  tail -n +2 $manifest_file | while IFS=, read -r destination_tar src_dir
  do
    pushd $(dirname $src_dir) &> /dev/null
    tar cf $backup_location/$destination_tar $(basename $src_dir)
    popd &> /dev/null
  done
}

function restore {
  logit "Running restore operation from $backup_location"
  tail -n +2 $manifest_file | while IFS=, read -r destination_tar src_dir
  do
    pushd $(dirname $src_dir) &> /dev/null
    tar xf $backup_location/$destination_tar $(basename $src_dir)
    popd &> /dev/null
  done
}

## Put your main code here.
function main {
  if [[ $restore == "true" ]]
  then
    restore
  else
    backup
  fi
}

## Boot strap the script. Nothing much to do here.
main "$@"
