#!/usr/bin/python3

'''
Inputs:
 - Project name - Required (must not have spaces)
 - Notes root path - Required (config)

Outputs:
 - A note folder
'''

import click
import readline
import re

from string import Template
from pathlib import Path


'''
Files that are created
 - Directory: <root path>/<project-name>
 - File: <root path>/<project-name>/Dashboard.md
 - File: <root path>/<project-name>/_helpers.md
 - File: <root path>/<project-name>/Notes.md
'''

notes_template = Template('''---
name: $project
type: project $tags
obsidianUIMode: preview
tags: $tags
---

Status:: $status

# Time Tracking

```button
name Start time $project
type command
action Shell Commands: Execute: Start Time
```
^button-start-$project

```button
name Stop time $project
type command
action Shell Commands: Execute: Stop Time
```

# Task Rollup

## Overdue

```tasks
due before today
not done
folder includes {{query.file.folder}}
```

## Due Today

```tasks
due today
not done
folder includes {{query.file.folder}}
```

## Due Tomorrow

```tasks
due tomorrow
not done
folder includes {{query.file.folder}}
```

## No Due Date

```tasks
no due date
not done
folder includes {{query.file.folder}}
```

## Done

```tasks
done
folder includes {{query.file.folder}}
```


''')


datetime_format = '%Y-%m-%d %H:%M'
date_format = '%Y-%m-%d'
year_format = '%Y'
valid_name_regex = re.compile(r'^[\w-]*$')
status_choices = click.Choice(['pending', 'in-progress', 'dropped', 'done', 'long-term', 'waiting'])


def get_valid_folder():
    readline.set_completer_delims('\t\n=')
    readline.parse_and_bind("tab: complete")
    option = input("Enter parent path for new project folder: ")
    path = Path(option).expanduser()

    while True:
        if path.is_dir():
            break
        else:
            if click.confirm(f'{path} does not exist. Create it?'):
                path.mkdir(parents=True, exist_ok=True)
                break
            else:
                option = input("Enter parent path for new project folder: ")
                path = Path(option).expanduser()
                continue

    return path


def get_valid_name():
    while True:
        name = click.prompt('Please provide a name for the project', type=str)
        if valid_name_regex.match(name):
            return name
        else:
            print('Invalid name. Names can only contain alphanumeric characters and - and _')


def main():
    project = get_valid_name()
    print(f'Got {project} as the project name')

    path = get_valid_folder()
    print(f'Got {path} as the parent path for the project')

    status = click.prompt('Current status', type=status_choices)
    print(f'Got {status} as the project status')

    tags = click.prompt('Tags, space separated', type=str, default='')

    note_path = path.joinpath(f'{project}.md')

    note = notes_template.substitute(project=project, tags=tags, status=status)

    with open(note_path, 'x') as f:
        f.write(note)

    print(f'Created a new project at {path}')


if __name__ == '__main__':
    main()
