#!/bin/bash

SHELL=/usr/bin/zsh

usage() {
echo "\
$0 <snap-pkg>
"
}

OPTSTRING=":h"

CLOSE=0
while getopts ${OPTSTRING} opt; do
  case ${opt} in
    h)
      usage
      exit 0
      ;;
    ?)
      echo "Invalid option: -${OPTARG}."
      usage
      exit 1
      ;;
  esac
done

if [[ -z $1 ]]
then
  echo "Please specify a snap name"
  usage
  exit -1
fi

MOUNT_DIR=$(mktemp -d)

if [[ "${1: -5}" != ".snap" ]]
then
  snap download ${1}
fi

sudo mount ${1}*.snap ${MOUNT_DIR} -t squashfs -o loop
pushd ${MOUNT_DIR}
/usr/bin/zsh -i
popd
sudo umount ${MOUNT_DIR}
sudo rmdir ${MOUNT_DIR}

if [[ "${1: -5}" != ".snap" ]]
then
  rm ${1}*.{snap,assert}
fi
